---
- hosts: all
  become: true
  tasks:
  
    - name: Instalar java
      yum:
        name: ['java-1.8.0-openjdk', 'wget', 'unzip']
        state: present
        
    - name: Crear grupo
      ansible.builtin.group:
        name: tomcat
        state: present
        
    - name: Crear usuario
      ansible.builtin.user:
        name: tomcat
        shell: /bin/nologin
        group: tomcat
        home: /opt/tomcat
        
    - name: Descomprimir paquete de TomCat
      ansible.builtin.unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53-deployer.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
        
    - name: Asignar permisos al grupo
      ansible.builtin.file:
       path: /opt/tomcat
       group: tomcat
       recurse: yes
       
    - name: Asignar permisos al directorio
      ansible.builtin.file:
        path: /opt/tomcat/conf
        recurse: yes
        mode: g=r
        
    - name: Asignar permisos al directorio y archivos
      ansible.builtin.file:
        path: /opt/tomcat/conf
        mode: g=x
        
    - name: Asignar permisos de owner
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: yes
        owner: tomcat
      loop:
        - /opt/tomcat/webapps/
        - /opt/tomcat/work/
        - /opt/tomcat/temp/
        - /opt/tomcat/logs/
        
    - name: Reiniciar tomcat y hacer daemon-reload para guardar configuraciones
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: tomcat
