---

- name: Instalar Wildfly
  hosts: all
  tasks:
  
  - name: Instalar paquete Java8
    apt:
      name: default-jdk
      state: latest
      
  - name: Asegurarse que el grupo "wildfly" existe
    group:
      name: wildfly
      state: present
      system: yes
      
  - name: Crear usuario wildfly
    user:
      name: wildfly
      system: yes
      group: wildfly
      home: /opt/wildfly2
      shell: /sbin/nologin
      
  - name: Crear link simbólico
    file:
      src: /opt/wildfly-22.0.1.Final
      dest: /opt/wildfly
      owner: wildfly
      group: wildfly
      state: link
      force: yes
      
  - name: Descargar wildfly
    get_url:
      url: https://download.jboss.org/wildfly/22.0.1.Final/wildfly-22.0.1.Final.zip
      dest: /root/wildflypkg.zip

  - name: Descomprimir wildfly
    unarchive:
      src: /root/wildflypkg.zip
      dest: /opt/
      copy: no
      
  - name: Cambiar recursivamente el owner de wildfly
    file:
      path: /opt/wildfly-22.0.1.Final
      owner: wildfly
      group: wildfly
      state: directory
      force: yes
      recurse: yes

  - name: Crear directorio para wildfly
    file:
      path: /etc/wildfly
      state: directory
      owner: wildfly
      group: wildfly
      
  - name: Copiar directorios al etc
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
      dest: /etc/wildfly/
      remote_src: yes
      
  - name: Copiar directorios al opt
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
      dest: /opt/wildfly/bin/
      remote_src: yes
      
  - name: Dar permisos de ejecución
    command: sh -c 'chmod +x /opt/wildfly/bin/*.sh'
    
  - name: Copiar directorio para crear el servicio
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
      dest: /lib/systemd/system
      remote_src: yes
      
  - name: Reiniciar daemons
    command: systemctl daemon-reload
    
  - name: Iniciar servicio
    command: systemctl start wildfly
    
  - name: Habilitar servicio
    command: systemctl enable wildfly
